import "./globals.css";
import Navbar from "../components/Navbar"
import Provider from "./utils/Provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  // 페이지가 존재하지 않는 경우 notFound 함수를 호출합니다.

  return (
    <html>
      <body>
        <Provider>
          <Navbar/>
          {children}
        </Provider>
      </body>
    </html>
  );
}