import "./globals.css";
import Navbar from "../components/Navbar"
import { LayoutProps } from "../types/types"
import QueryProvider from "./utils/QueryProvider";
import AuthProvider from "./utils/AuthProvider"
import RecoilProvider from "./utils/RecoilProvider"
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import dynamic from 'next/dynamic';
const GoogleAnalytics = dynamic(() => import('./googleAnalytics'), {
  ssr: false,
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps) {
  // 페이지가 존재하지 않는 경우 notFound 함수를 호출합니다.

  return (
    <html>
      <body>
        <RecoilProvider>  
          <QueryProvider>
            <AuthProvider>  
              <Navbar />
              <div className="pt-[52px]">
                {children}
                <GoogleAnalytics GA_TRACKING_ID={process.env.NEXT_PUBLIC_GA_ID} />
                <ToastContainer autoClose={1000} pauseOnFocusLoss={false} pauseOnHover={false}/>
              </div>
            </AuthProvider>
          </QueryProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}